_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 5
                - 13
                - 14
                - 23
                - 55
                - 62
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 6
            "12": 0.18.7
            "13": linux-x86_64
