_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 14
                - 23
                - 24
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 6
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 12
input_size:
    value:
        - 128
        - 128
learning_rate:
    value: 0.002
